#!/usr/bin/env ruby

# frozen_string_literal: true

require 'readline'

require './lib/zaid/interpreter'

def format_value(value)
  if value.nil?
    'مجهول'
  elsif value == true
    'صحيح'
  elsif value == false
    'خاطئ'
  else
    value.inspect
  end
end

interpreter = Zaid::Interpreter.new

if (file = ARGV.first)
  interpreter.eval(File.read(file))
else
  puts 'مُفسِّر لغة زيد | اضغط CTRL+C للخروج'

  loop do
    line = Readline.readline('>> ')

    break if line.nil?

    Readline::HISTORY.push(line)
    value = interpreter.eval(line)

    if value.respond_to?(:ruby_value)
      puts "=> #{format_value(value.ruby_value)}"
    else
      puts "=> #{format_value(value)}"
    end
  rescue Interrupt
    break
  end
end
