# frozen_string_literal: true

require_relative 'nodes/array_access_node'
require_relative 'nodes/array_assignment_node'
require_relative 'nodes/array_node'
require_relative 'nodes/break_node'
require_relative 'nodes/call_node'
require_relative 'nodes/class_node'
require_relative 'nodes/continue_node'
require_relative 'nodes/false_node'
require_relative 'nodes/float_node'
require_relative 'nodes/get_constant_node'
require_relative 'nodes/get_local_node'
require_relative 'nodes/if_node'
require_relative 'nodes/literal_node'
require_relative 'nodes/method_node'
require_relative 'nodes/nil_node'
require_relative 'nodes/node_list'
require_relative 'nodes/number_node'
require_relative 'nodes/set_constant_node'
require_relative 'nodes/set_local_node'
require_relative 'nodes/string_node'
require_relative 'nodes/true_node'
require_relative 'nodes/while_node'
